### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by mab-mab** [kaduvert/mineflayer-griefergames#1]
Hi, ich finde das Projekt sehr interessant. Den großteil habe ich mittlerweile ohne docs verstanden. Eine Frage habe ich aber noch. Ist irgendwo zu sehen welche parameter ein event zurückgibt. z.B. `bot.on("chat:chat->playerMessage")`. hier konnte ich nirgendwo finden, wo definiert ist das die parameter (rank, username, message) mitgegeben werden. Ein verweis auf den entsprechenden code würde mir reichen,. Danke

**Comment by mab-mab** [comment]
Wie ich sehe ist es immer ein parameter als array

**Comment by kaduvert** [comment]
bei chat: events ist das wieviele capture groups im regex sind, z.B.:
Text: Ich habe 5€
Regex: /^(\S+) habe (\S+)$/

wegen multiline support etc wird das ein arr und der regex auch (jede capture group 1 arg), das wäre dann so: [ [ wer, wieviel ] ]
genau, also es ist leider nirgends dokumentiert was da genau zurückkommt, die werte werden eigentlich erst im listener benannt...

WAS TUN?
eventquelle anschauen und evtl misc: event herstellen und als PR hier reinmergen.

**Comment by kaduvert** [comment]
Hi,
bei chat: events ist das wieviele capture groups im regex sind, z.B.:
Text: Ich habe 5€
Regex: /^(\S+) habe (\S+)$/

wegen multiline support etc wird das ein arr und der regex auch (jede capture group 1 arg), das wäre dann so: [ [ wer, wieviel ] ]
genau, also es ist leider nirgends dokumentiert was da genau zurückkommt, die werte werden eigentlich erst im listener benannt...

WAS TUN?
eventquelle anschauen und evtl misc: event herstellen und als PR hier reinmergen.

regexe und sowas sind btw alle in mineflayer-griefergames-data

**Comment by kaduvert** [comment]
genau aber eigentlich sollte das alles nicht so schwer sein, in den meisten fällen steht ja im regex kurz vor oder nach der capture group um was es sich handelt, z.B. bei plot info steht ja immer genau was was ist, Besitzer: (...), Alias: (...), Vertraut: (...), etc.

### und dieses issue ist ab jetzt FAQ

d.h. jeder der Fragen hat kann hier kommentieren und ich werde vermutlich antworten (sofern es nicht um JavaScript geht oder um sachen die man sehr leicht selbst herausfinden könnte)

**Comment by mab-mab** [comment]
Hi nochmal, wenn ich probiere auf einen Spawner zuzugreifen, mit der funktion `bot.gg.spawner.tryToOpen()` , wir das nie als succes anerkannt, obwohl ich mit einem anderen account nicht auf den spawner zugreifen kann, weil mein anderer acc ihn geöffnet hat

**Comment by kaduvert** [comment]
möglicherweise entspricht das spawner window nicht mehr dem was es war wo der code geschrieben wurde und deswegen wird es nicht erkannt.
aber kp.
du kannst dafür aber gerne ein richtiges issue eröffnen

**Comment by kaduvert** [comment]
also spawner code sehr outdated, vielleicht is jetzt gefixed.
probier mal mit ```
"mineflayer-griefergames": "github:kaduvert/mineflayer-griefergames"
```
als dependency im package.json und sag obs klappt

**Comment by kaduvert** [comment]
https://github.com/kaduvert/mineflayer-griefergames/discussions/4
