### ISSUE TITLE
Spawner

### ISSUE THREAD

**Issue by mab-mab** [kaduvert/mineflayer-griefergames#3]
Wie bereits erwähnt will der spawner igwie nicht. Vllt bin ich auch zu blöd, bin in javascript nicht so dabei. hier mal mein code:
![image](https://github.com/user-attachments/assets/246d9a8d-1df1-45f7-b377-f14bbe67ab84)

da die function getLootableStacks() ein window als inout benötigt, dachte ich getWindow() würde klappen, allerdings nicht.
der code Oben gibt ebenfalls für succesS und failure beides mal false aus

**Comment by kaduvert** [comment]
ja genau, also dein code ist eigentlich richtig, das beides mal false kommt liegt daran, das weder ein failureEvent noch ein successEvent getriggert wird (timeout tritt ein).

versuch mal:
```npm install github:kaduvert/mineflayer-griefergames```

und probiers nochmal.

getWindow() auf dem result funktioniert, aber nunmal nur wenn hasSucceeded() true ist

**Comment by mab-mab** [comment]
![image](https://github.com/user-attachments/assets/d0eba9bf-8c03-4ffd-8b5f-14ad35420e75)
leider mit dem code immer noch false als hasSucceeded(), ka woran das liegt, spawner ist laut ingame immern noch geöffnet

**Comment by kaduvert** [comment]
auf jeden fall jetzt gefixt mit 0bdb412 (npm version 0.1.7), hab ingame getestet, gab noch einige fehler aber window lies sich auf jeden fall öffnen und mit 0.1.7 geht auch looten und so wieder.

wenn du updatest stell sicher das du nicht alte versionen irgendwie verwendest, also irgendwelche caches wie node_modules am besten clearen um sicher zu sein.
