### ISSUE TITLE
Chest Depositing

### ISSUE THREAD

**Issue by mab-mab** [kaduvert/mineflayer-griefergames#5]
Beim depositen von Items in eine Chest kommt häufig dieser Fehler `Error: Server didn't respond to transaction for clicking on slot 3 on window with id 0.`. Hast du damit erfahrung oder das gleiche schonmal erlebt? Ist zwar von mineflayer selbst aber vllt liegt das an griefergames

**Comment by kaduvert** [comment]
ja liegt an griefergames, musst kleine cooldowns, aggressives retrying und erfolgschecks einbaun damit das vernünftig und zuverlässig funktioniert

ist mir zu kompliziert und aufwendig gute universelle window functions hier einzubauen.
wenn du geld in die hand nehmen willst kann ich dir aber das passende für deine zwecke coden. add mich dazu auf dc, name gleich wie hier. rechne mit so 70€ für komplettpaket windows handlen

**Comment by mab-mab** [comment]
Danke für die Antwort. Verstehe das das dir zu aufwendig ist, trotzdem danke für die Tipps. Werde es zunächst selber versuchen, merke mir aber dein Angebot 👍
